### ISSUE TITLE
Response adding "print"

### ISSUE THREAD

**Issue by MattPo** [thbaumbach/node-quake3-rcon#4]
Hello! I really don't think you want to work on this package anymore, but I've recently found it, and it's fitting my need perfectly. However, I have a small issue with responses inserting "print" at the start of the response, and then every 1000 characters or so.

Any idea what would be causing this, or what I could do to work around it?  If you're able to help, it would be appreciated.

**Examples**
_rcon serverinfo_

print <------
Server info settings:
sv_maxclients        30
version              CoD4 X - linux-i386 build 962 Mar 12 2019
shortversion         -
build                962
branch               dev_newarch

_rcon status_ (in bold)

**print**
map: mp_crash
num score ping guid                             name            lastmsg address               qport rate
--- ----- ---- -------------------------------- --------------- ------- --------------------- ----- -----
  2    47  219 2310346617288258243              BockLandes^7            0 999.148.69.245:28960  27080 100000
  4    30  189 2310346615351783804              Satan^7                50 999.89.199.128:62100  45177 100000
  6    47   64 2310346613751016972              RitZz JD-I^7         50 999.250.95.164:60773  34240 100000
  8   119   72 2310346616055939769              FaNaT^7                 0 999.109.24.140:28960  17643 100000
  9    69   56 2310346613459929248              Morcegam^7             50 999.37.11.27:28960    54339 100000
 10    54  172 2310346615138301380              Cuervo^7                0 999.249.208.216:18078  27741 100000
 11    27  185 2310346614342378295              Johnny^7               50 999.234.215.181:28960  34188 100000
 13    46  151**print**
2310346613553464866              Talha^7                50 999.201.131.232:14289  45413 100000
 14    45   67 2310346614254859697              enFF^7                  0 999.230.25.181:11650   60249 100000
 15   107   43 2310346616823883199              LEGz AIMBOTTT^7         0 999.162.85.14:28960    42668 100000
 16    37   46 2310346613514424766              Fox1Lead^7            900 999.146.198.37:38080    44720 100000
 17    72   32 2310346614501231356              wayne^7                50 999.100.80.222:28960   36618 100000
 19    34  210 2310346614053634727              |LI|RussianPooH^7      50 999.95.88.68:28960    43288 100000

**Comment by ThatZiv** [comment]
You could just replace the *print* string with an empty one.
Example: 
```js
'use strict';
const Rcon = require("quake3-rcon")
let r = Rcon({...})
r.send("serverinfo", function(response) {
   let actual_response = response.replace("print ", "")
   console.log(actual_response)
})
// output should have everything besides that print str
```

**Comment by thbaumbach** [comment]
👀
